# Generated by Django 4.2 on 2026-03-07 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Event', max_length=200)),
                ('event_type', models.CharField(choices=[('hearing', 'Court Hearing'), ('meeting', 'Client Meeting'), ('deadline', 'Deadline'), ('other', 'Other')], default='hearing', max_length=20)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
